/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RichiesteRouteImport } from './routes/richieste'
import { Route as ReportRouteImport } from './routes/report'
import { Route as PresenzeRouteImport } from './routes/presenze'
import { Route as NovitaRouteImport } from './routes/novita'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as AmministrazioneRouteImport } from './routes/amministrazione'
import { Route as IndexRouteImport } from './routes/index'

const RichiesteRoute = RichiesteRouteImport.update({
  id: '/richieste',
  path: '/richieste',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportRoute = ReportRouteImport.update({
  id: '/report',
  path: '/report',
  getParentRoute: () => rootRouteImport,
} as any)
const PresenzeRoute = PresenzeRouteImport.update({
  id: '/presenze',
  path: '/presenze',
  getParentRoute: () => rootRouteImport,
} as any)
const NovitaRoute = NovitaRouteImport.update({
  id: '/novita',
  path: '/novita',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AmministrazioneRoute = AmministrazioneRouteImport.update({
  id: '/amministrazione',
  path: '/amministrazione',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/amministrazione': typeof AmministrazioneRoute
  '/dashboard': typeof DashboardRoute
  '/novita': typeof NovitaRoute
  '/presenze': typeof PresenzeRoute
  '/report': typeof ReportRoute
  '/richieste': typeof RichiesteRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/amministrazione': typeof AmministrazioneRoute
  '/dashboard': typeof DashboardRoute
  '/novita': typeof NovitaRoute
  '/presenze': typeof PresenzeRoute
  '/report': typeof ReportRoute
  '/richieste': typeof RichiesteRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/amministrazione': typeof AmministrazioneRoute
  '/dashboard': typeof DashboardRoute
  '/novita': typeof NovitaRoute
  '/presenze': typeof PresenzeRoute
  '/report': typeof ReportRoute
  '/richieste': typeof RichiesteRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/amministrazione'
    | '/dashboard'
    | '/novita'
    | '/presenze'
    | '/report'
    | '/richieste'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/amministrazione'
    | '/dashboard'
    | '/novita'
    | '/presenze'
    | '/report'
    | '/richieste'
  id:
    | '__root__'
    | '/'
    | '/amministrazione'
    | '/dashboard'
    | '/novita'
    | '/presenze'
    | '/report'
    | '/richieste'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AmministrazioneRoute: typeof AmministrazioneRoute
  DashboardRoute: typeof DashboardRoute
  NovitaRoute: typeof NovitaRoute
  PresenzeRoute: typeof PresenzeRoute
  ReportRoute: typeof ReportRoute
  RichiesteRoute: typeof RichiesteRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/richieste': {
      id: '/richieste'
      path: '/richieste'
      fullPath: '/richieste'
      preLoaderRoute: typeof RichiesteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/report': {
      id: '/report'
      path: '/report'
      fullPath: '/report'
      preLoaderRoute: typeof ReportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/presenze': {
      id: '/presenze'
      path: '/presenze'
      fullPath: '/presenze'
      preLoaderRoute: typeof PresenzeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/novita': {
      id: '/novita'
      path: '/novita'
      fullPath: '/novita'
      preLoaderRoute: typeof NovitaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/amministrazione': {
      id: '/amministrazione'
      path: '/amministrazione'
      fullPath: '/amministrazione'
      preLoaderRoute: typeof AmministrazioneRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AmministrazioneRoute: AmministrazioneRoute,
  DashboardRoute: DashboardRoute,
  NovitaRoute: NovitaRoute,
  PresenzeRoute: PresenzeRoute,
  ReportRoute: ReportRoute,
  RichiesteRoute: RichiesteRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
