/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as SupervisioneRouteImport } from './routes/supervisione'
import { Route as RichiesteRouteImport } from './routes/richieste'
import { Route as ReportRouteImport } from './routes/report'
import { Route as ProcurementRouteImport } from './routes/procurement'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as PresenzeRouteImport } from './routes/presenze'
import { Route as NovitaRouteImport } from './routes/novita'
import { Route as GestioneTimbratureRouteImport } from './routes/gestione-timbrature'
import { Route as FinanzaRouteImport } from './routes/finanza'
import { Route as DocumentiRouteImport } from './routes/documenti'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as CronBancaRouteImport } from './routes/cron-banca'
import { Route as ComunicazioniRouteImport } from './routes/comunicazioni'
import { Route as AmministrazioneRouteImport } from './routes/amministrazione'
import { Route as IndexRouteImport } from './routes/index'

const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const SupervisioneRoute = SupervisioneRouteImport.update({
  id: '/supervisione',
  path: '/supervisione',
  getParentRoute: () => rootRouteImport,
} as any)
const RichiesteRoute = RichiesteRouteImport.update({
  id: '/richieste',
  path: '/richieste',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportRoute = ReportRouteImport.update({
  id: '/report',
  path: '/report',
  getParentRoute: () => rootRouteImport,
} as any)
const ProcurementRoute = ProcurementRouteImport.update({
  id: '/procurement',
  path: '/procurement',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const PresenzeRoute = PresenzeRouteImport.update({
  id: '/presenze',
  path: '/presenze',
  getParentRoute: () => rootRouteImport,
} as any)
const NovitaRoute = NovitaRouteImport.update({
  id: '/novita',
  path: '/novita',
  getParentRoute: () => rootRouteImport,
} as any)
const GestioneTimbratureRoute = GestioneTimbratureRouteImport.update({
  id: '/gestione-timbrature',
  path: '/gestione-timbrature',
  getParentRoute: () => rootRouteImport,
} as any)
const FinanzaRoute = FinanzaRouteImport.update({
  id: '/finanza',
  path: '/finanza',
  getParentRoute: () => rootRouteImport,
} as any)
const DocumentiRoute = DocumentiRouteImport.update({
  id: '/documenti',
  path: '/documenti',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const CronBancaRoute = CronBancaRouteImport.update({
  id: '/cron-banca',
  path: '/cron-banca',
  getParentRoute: () => rootRouteImport,
} as any)
const ComunicazioniRoute = ComunicazioniRouteImport.update({
  id: '/comunicazioni',
  path: '/comunicazioni',
  getParentRoute: () => rootRouteImport,
} as any)
const AmministrazioneRoute = AmministrazioneRouteImport.update({
  id: '/amministrazione',
  path: '/amministrazione',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/amministrazione': typeof AmministrazioneRoute
  '/comunicazioni': typeof ComunicazioniRoute
  '/cron-banca': typeof CronBancaRoute
  '/dashboard': typeof DashboardRoute
  '/documenti': typeof DocumentiRoute
  '/finanza': typeof FinanzaRoute
  '/gestione-timbrature': typeof GestioneTimbratureRoute
  '/novita': typeof NovitaRoute
  '/presenze': typeof PresenzeRoute
  '/privacy': typeof PrivacyRoute
  '/procurement': typeof ProcurementRoute
  '/report': typeof ReportRoute
  '/richieste': typeof RichiesteRoute
  '/supervisione': typeof SupervisioneRoute
  '/terms': typeof TermsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/amministrazione': typeof AmministrazioneRoute
  '/comunicazioni': typeof ComunicazioniRoute
  '/cron-banca': typeof CronBancaRoute
  '/dashboard': typeof DashboardRoute
  '/documenti': typeof DocumentiRoute
  '/finanza': typeof FinanzaRoute
  '/gestione-timbrature': typeof GestioneTimbratureRoute
  '/novita': typeof NovitaRoute
  '/presenze': typeof PresenzeRoute
  '/privacy': typeof PrivacyRoute
  '/procurement': typeof ProcurementRoute
  '/report': typeof ReportRoute
  '/richieste': typeof RichiesteRoute
  '/supervisione': typeof SupervisioneRoute
  '/terms': typeof TermsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/amministrazione': typeof AmministrazioneRoute
  '/comunicazioni': typeof ComunicazioniRoute
  '/cron-banca': typeof CronBancaRoute
  '/dashboard': typeof DashboardRoute
  '/documenti': typeof DocumentiRoute
  '/finanza': typeof FinanzaRoute
  '/gestione-timbrature': typeof GestioneTimbratureRoute
  '/novita': typeof NovitaRoute
  '/presenze': typeof PresenzeRoute
  '/privacy': typeof PrivacyRoute
  '/procurement': typeof ProcurementRoute
  '/report': typeof ReportRoute
  '/richieste': typeof RichiesteRoute
  '/supervisione': typeof SupervisioneRoute
  '/terms': typeof TermsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/amministrazione'
    | '/comunicazioni'
    | '/cron-banca'
    | '/dashboard'
    | '/documenti'
    | '/finanza'
    | '/gestione-timbrature'
    | '/novita'
    | '/presenze'
    | '/privacy'
    | '/procurement'
    | '/report'
    | '/richieste'
    | '/supervisione'
    | '/terms'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/amministrazione'
    | '/comunicazioni'
    | '/cron-banca'
    | '/dashboard'
    | '/documenti'
    | '/finanza'
    | '/gestione-timbrature'
    | '/novita'
    | '/presenze'
    | '/privacy'
    | '/procurement'
    | '/report'
    | '/richieste'
    | '/supervisione'
    | '/terms'
  id:
    | '__root__'
    | '/'
    | '/amministrazione'
    | '/comunicazioni'
    | '/cron-banca'
    | '/dashboard'
    | '/documenti'
    | '/finanza'
    | '/gestione-timbrature'
    | '/novita'
    | '/presenze'
    | '/privacy'
    | '/procurement'
    | '/report'
    | '/richieste'
    | '/supervisione'
    | '/terms'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AmministrazioneRoute: typeof AmministrazioneRoute
  ComunicazioniRoute: typeof ComunicazioniRoute
  CronBancaRoute: typeof CronBancaRoute
  DashboardRoute: typeof DashboardRoute
  DocumentiRoute: typeof DocumentiRoute
  FinanzaRoute: typeof FinanzaRoute
  GestioneTimbratureRoute: typeof GestioneTimbratureRoute
  NovitaRoute: typeof NovitaRoute
  PresenzeRoute: typeof PresenzeRoute
  PrivacyRoute: typeof PrivacyRoute
  ProcurementRoute: typeof ProcurementRoute
  ReportRoute: typeof ReportRoute
  RichiesteRoute: typeof RichiesteRoute
  SupervisioneRoute: typeof SupervisioneRoute
  TermsRoute: typeof TermsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/supervisione': {
      id: '/supervisione'
      path: '/supervisione'
      fullPath: '/supervisione'
      preLoaderRoute: typeof SupervisioneRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/richieste': {
      id: '/richieste'
      path: '/richieste'
      fullPath: '/richieste'
      preLoaderRoute: typeof RichiesteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/report': {
      id: '/report'
      path: '/report'
      fullPath: '/report'
      preLoaderRoute: typeof ReportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/procurement': {
      id: '/procurement'
      path: '/procurement'
      fullPath: '/procurement'
      preLoaderRoute: typeof ProcurementRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/presenze': {
      id: '/presenze'
      path: '/presenze'
      fullPath: '/presenze'
      preLoaderRoute: typeof PresenzeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/novita': {
      id: '/novita'
      path: '/novita'
      fullPath: '/novita'
      preLoaderRoute: typeof NovitaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gestione-timbrature': {
      id: '/gestione-timbrature'
      path: '/gestione-timbrature'
      fullPath: '/gestione-timbrature'
      preLoaderRoute: typeof GestioneTimbratureRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/finanza': {
      id: '/finanza'
      path: '/finanza'
      fullPath: '/finanza'
      preLoaderRoute: typeof FinanzaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/documenti': {
      id: '/documenti'
      path: '/documenti'
      fullPath: '/documenti'
      preLoaderRoute: typeof DocumentiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cron-banca': {
      id: '/cron-banca'
      path: '/cron-banca'
      fullPath: '/cron-banca'
      preLoaderRoute: typeof CronBancaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/comunicazioni': {
      id: '/comunicazioni'
      path: '/comunicazioni'
      fullPath: '/comunicazioni'
      preLoaderRoute: typeof ComunicazioniRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/amministrazione': {
      id: '/amministrazione'
      path: '/amministrazione'
      fullPath: '/amministrazione'
      preLoaderRoute: typeof AmministrazioneRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AmministrazioneRoute: AmministrazioneRoute,
  ComunicazioniRoute: ComunicazioniRoute,
  CronBancaRoute: CronBancaRoute,
  DashboardRoute: DashboardRoute,
  DocumentiRoute: DocumentiRoute,
  FinanzaRoute: FinanzaRoute,
  GestioneTimbratureRoute: GestioneTimbratureRoute,
  NovitaRoute: NovitaRoute,
  PresenzeRoute: PresenzeRoute,
  PrivacyRoute: PrivacyRoute,
  ProcurementRoute: ProcurementRoute,
  ReportRoute: ReportRoute,
  RichiesteRoute: RichiesteRoute,
  SupervisioneRoute: SupervisioneRoute,
  TermsRoute: TermsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
